version: '3.7'

services:
  app:
    container_name: mybody_test_articles
    build:
      dockerfile: dockerfile
    environment:
      MODULE_NAME: "main"
      MAX_WORKERS: 2
    ports:
      - "4012:80"